import "./globals.css";
import type { Metadata } from "next";
import { ReactNode } from "react";
import MuiThemeProvider from "./MuiThemeProvider";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
  children: ReactNode;
}>) {
    return (
        <html lang="es">
            <head>
                <link rel="stylesheet" href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css' />
            </head>
            <body
                className={`antialiased`}
            >
                <MuiThemeProvider>
                    {children}
                </MuiThemeProvider>
            </body>
        </html>
    );
}
