import "./globals.css";
import MantineCustomProvider from "@/components/providers/MantineProvider";
import type { Metadata } from "next";
import { ReactNode } from "react";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
  children: ReactNode;
}>) {
    return (
        <html lang="es">
            <body
                className={`antialiased`}
            >
                <MantineCustomProvider>
                    {children}
                </MantineCustomProvider>
            </body>
        </html>
    );
}
